Section A: Data Structures & Control Structures

1. List operations

In [1]:
aiki=[10,12,22,40,50]

In [2]:
aiki.append(60) #append

In [3]:
aiki

[10, 12, 22, 40, 50, 60]

In [4]:
aiki.extend([70,80]) #extending numbers

In [5]:
aiki

[10, 12, 22, 40, 50, 60, 70, 80]

In [10]:
aiki.insert(9,100) #insering 

In [11]:
aiki

[10, 12, 22, 40, 50, 98, 60, 70, 80, 100, 98]

In [13]:
aiki.remove(70)

In [14]:
aiki

[10, 12, 22, 40, 50, 98, 60, 80, 100, 98]

In [15]:
aiki.pop()

98

In [16]:
aiki

[10, 12, 22, 40, 50, 98, 60, 80, 100]

In [21]:
aiki.clear()

In [22]:
aiki

[]

In [26]:
aiki=[10,12,22,40,50,60,80,98,100]

In [28]:
aiki.index(100)

8

In [35]:
aiki.count(100)

1

In [36]:
aiki.reverse()

In [38]:
aiki

[100, 98, 80, 60, 50, 40, 22, 12, 10]

In [39]:
aiki.sort()

In [40]:
aiki

[10, 12, 22, 40, 50, 60, 80, 98, 100]

 Tuples

In [41]:
students=("aiki","buddy","bob")

In [42]:
students

('aiki', 'buddy', 'bob')

In [45]:
students[1]="aceent"

TypeError: 'tuple' object does not support item assignment

Tuples are immutable, so their elements cannot be changed after creation.

 Sets

In [46]:
setss={1,2,2,3,4,5,6,7,8,9,10,11,12,12,12,98,98,99,99,100,100}

In [47]:
setss

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 98, 99, 100}

Sets automatically remove duplicate elements. The output will contain only unique values.

Dictionary 

In [49]:
informations={
    "Name":"aiki",
    "age":22,
    "city":"bangalore"
}

In [50]:
informations

{'Name': 'aiki', 'age': 22, 'city': 'bangalore'}

In [51]:
informations["age"]=23

In [52]:
informations

{'Name': 'aiki', 'age': 23, 'city': 'bangalore'}

In [53]:
informations["e-mails"]="aiki22gmail.com"

In [54]:
informations

{'Name': 'aiki', 'age': 23, 'city': 'bangalore', 'e-mails': 'aiki22gmail.com'}

Voting eligibility check

In [55]:
age=int(input())
if age>=18:
    print("you are eligible for voting")
else:
    print("you are not eligible for voting")

 22


you are eligible for voting


Grade based on marks

In [71]:
number=int(input())
if number>=90:
    print("grade is : A")
elif 75<= number <=89:
    print("grade is : B")
elif 50<=  number <=74:
    print("grade is : C")
else:
    print("failed")
    

 100


grade is : A


In [88]:
number=int(input())
if number>0:
    if number%2==0:
        print(number,"is both even and positive")
elif number==0:
    print(number,"the given number is zero")
else:
    print(number,"the given number is negative")

 100


100 is both even and positive


Section B: Numpy and Pandas

In [90]:
import numpy as np

In [93]:
scalers=np.array(5)

In [94]:
scalers

array(5)

In [95]:
array_1d=np.array([10,12,22,98,100])

In [96]:
array_1d

array([ 10,  12,  22,  98, 100])

In [99]:
array_2d=np.array([[1,2,3,4,5],[10,12,22,98,100]])

In [100]:
array_2d

array([[  1,   2,   3,   4,   5],
       [ 10,  12,  22,  98, 100]])

In [101]:
random_arrays=np.random.randint(1,100,size=(4,4))

In [102]:
random_arrays

array([[53, 99, 60, 80],
       [36, 96, 64, 35],
       [20, 35, 21, 90],
       [87, 60, 15,  2]], dtype=int32)

In [118]:
arrays=np.array([[53, 99, 60],
       [36, 96, 64],
       [20,  21, 90]],)

In [119]:
import pandas as pd

In [120]:
arrays

array([[53, 99, 60],
       [36, 96, 64],
       [20, 21, 90]])

In [122]:
pd.DataFrame(arrays,columns=["A","K","AI"])

A   K  AI
0  53  99  60
1  36  96  64
2  20  21  90

In [222]:
datas={
    "Name":["aiki","ai","ki","sh","ra","ds","spark","sql","data","nlp"],
    "Age":[22,23,24,25,26,27,22,23,28,29],
    "city":["bangalore","mysore","chenai","hyderabad","delhi","pune","rajastan","hyderabad","rajastan","delhi"],
    "salary":[9909900000,9809800000,9923233237,8565656576,9798766678,7687656765, np.nan ,7575474565,9769766879,6654654656]
}

In [223]:
datas

{'Name': ['aiki', 'ai', 'ki', 'sh', 'ra', 'ds', 'spark', 'sql', 'data', 'nlp'],
 'Age': [22, 23, 24, 25, 26, 27, 22, 23, 28, 29],
 'city': ['bangalore',
  'mysore',
  'chenai',
  'hyderabad',
  'delhi',
  'pune',
  'rajastan',
  'hyderabad',
  'rajastan',
  'delhi'],
 'salary': [9909900000,
  9809800000,
  9923233237,
  8565656576,
  9798766678,
  7687656765,
  nan,
  7575474565,
  9769766879,
  6654654656]}

In [224]:
df=pd.DataFrame(datas)

In [225]:
df

Name  Age       city        salary
0   aiki   22  bangalore  9.909900e+09
1     ai   23     mysore  9.809800e+09
2     ki   24     chenai  9.923233e+09
3     sh   25  hyderabad  8.565657e+09
4     ra   26      delhi  9.798767e+09
5     ds   27       pune  7.687657e+09
6  spark   22   rajastan           NaN
7    sql   23  hyderabad  7.575475e+09
8   data   28   rajastan  9.769767e+09
9    nlp   29      delhi  6.654655e+09

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   city    10 non-null     object 
 3   salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [227]:
df[["Name","city"]]

Name       city
0   aiki  bangalore
1     ai     mysore
2     ki     chenai
3     sh  hyderabad
4     ra      delhi
5     ds       pune
6  spark   rajastan
7    sql  hyderabad
8   data   rajastan
9    nlp      delhi

In [228]:
df.drop(columns="city")

Name  Age        salary
0   aiki   22  9.909900e+09
1     ai   23  9.809800e+09
2     ki   24  9.923233e+09
3     sh   25  8.565657e+09
4     ra   26  9.798767e+09
5     ds   27  7.687657e+09
6  spark   22           NaN
7    sql   23  7.575475e+09
8   data   28  9.769767e+09
9    nlp   29  6.654655e+09

In [229]:
df["salary"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: salary, dtype: bool

In [230]:
df.isnull().sum()

Name      0
Age       0
city      0
salary    1
dtype: int64

In [231]:
df["salary"].fillna(df["salary"].mean(),inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_40676\3472753723.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["salary"].fillna(df["salary"].mean(),inplace=True)


In [232]:
df

Name  Age       city        salary
0   aiki   22  bangalore  9.909900e+09
1     ai   23     mysore  9.809800e+09
2     ki   24     chenai  9.923233e+09
3     sh   25  hyderabad  8.565657e+09
4     ra   26      delhi  9.798767e+09
5     ds   27       pune  7.687657e+09
6  spark   22   rajastan  8.854990e+09
7    sql   23  hyderabad  7.575475e+09
8   data   28   rajastan  9.769767e+09
9    nlp   29      delhi  6.654655e+09

In [233]:
df.duplicated().sum()

np.int64(0)

In [234]:
df.drop_duplicates()

Name  Age       city        salary
0   aiki   22  bangalore  9.909900e+09
1     ai   23     mysore  9.809800e+09
2     ki   24     chenai  9.923233e+09
3     sh   25  hyderabad  8.565657e+09
4     ra   26      delhi  9.798767e+09
5     ds   27       pune  7.687657e+09
6  spark   22   rajastan  8.854990e+09
7    sql   23  hyderabad  7.575475e+09
8   data   28   rajastan  9.769767e+09
9    nlp   29      delhi  6.654655e+09

In [235]:
df["city"].duplicated().sum()

np.int64(3)

In [244]:
df["city"].drop_duplicates(inplace=True,ignore_index=True)

In [248]:
df[["city"]].drop_duplicates()

city
0  bangalore
1     mysore
2     chenai
3  hyderabad
4      delhi
5       pune
6   rajastan